### PR TITLE
Update Jenkinsfile

### PR DESCRIPTION
**Pull request by graphwire**

### CODE REVIEW

**Comment by pollockm** [comment]
@graphwire  - Why is the version bumped from 2014 to 2018?  We normally keep DCAF modules built in the earliest version that supports the features needed by the module.

**Comment by pollockm** [comment]
@graphwire  - If you have any questions, feel free to ask!

**Comment by graphwire** [comment]
Sorry for that! I copied the repository for testing purposes and made a pull request to the original one instead of mine. Thank you for rejecting it! :-) 
I am trying to setup the CI buildsystem, got an error and thought maybe it's the LV version. Then I realized that the pipelineBuild method was missing. It would be great if we had some more detailed information on the global library settings in the CLI tutorial.pdf. I am still in the process of making it work.
Overall great work! It's been very helpful!

**Comment by pollockm** [comment]
If you're just starting to get a CI system stood up, you might want to look at https://github.com/ni/niveristand-custom-device-build-tools - that's essentially the next evolution of the tools we first prototyped here.  It no longer requires any additional VI Packages (Wiresmith CLI, CLI steps), instead relying on the recently released LabVIEW CLI that shipped in the 2018 version, which works with all versions 2014 and later (http://www.ni.com/download/labview-command-line-interface-1.1/8090/en/)

**Comment by graphwire** [comment]
You sir are very helpful! Thanks a bunch! Yes actually I have been using Jenkins with SVN for quite a while now. At the moment we are transitioning from a plugin architecture with a single exe to multiple ppls and it has been painful finding the right tools for CI. The ultimate goal would be  to automate the triggering of the build only for the libraries where a change has occurred and if required for the children of the classes and possibly the callers of the library. The "Build-Time dependencies" feature seems to be what I was looking for...  I was about to start coding such a thing :-) ! Have you been using these tools? Are you maybe aware of a solution for a similar case? It seems that VeriStand comes included in the Labview Professional edition if I am not mistaken, which makes it tempting! Thanks again!

**Pull request closed without merging**
